### ISSUE TITLE
ubuntu build error

### ISSUE THREAD

**Issue by makc** [acgessler/assimp2json#20]
I am trying to run `make assimp2json` after `cmake ./` and I get this:
![screen shot 2016-12-06 at 21 26 05](https://cloud.githubusercontent.com/assets/242577/20942306/28c0627e-bbfb-11e6-90aa-e92ca845aa08.png)

I was thinking where do I add that -fPIC flag, and opened flags.make, and it was already there:
![screen shot 2016-12-06 at 21 25 29](https://cloud.githubusercontent.com/assets/242577/20942345/4f5f053e-bbfb-11e6-89cd-b74a20457b29.png)

What am I doing wrong? Thanks.

**Comment by kimkulling** [comment]
You need to enable this flag for yor executable as well.

**Comment by makc** [comment]
But how come this builds perfectly fine on mac, but not so on ubuntu, what's the difference? I did exact same thing on both, mac is fine, ubuntu -> build error.

**Comment by makc** [comment]
Also, tried to do
```
cmake -DCMAKE_CXX_FLAGS=-fPIC ./
make assimp2json
```
as per [this comment](https://github.com/assimp/assimp/issues/634#issuecomment-136985088), but the error did not go away.

**Comment by makc** [comment]
ok, yet another version [here](https://github.com/assimp/assimp/issues/746) says to also specify -DCMAKE_C_FLAGS=-fPIC **edit** ok that does it.

**Comment by agirault** [comment]
If using CMake, prefer the use of [CMAKE_POSITION_INDEPENDENT_CODE](https://cmake.org/cmake/help/v3.4/variable/CMAKE_POSITION_INDEPENDENT_CODE.html), instead of manually editing the flags.

> https://stackoverflow.com/questions/38296756/what-is-the-idiomatic-way-in-cmake-to-add-the-fpic-compiler-option
