### ISSUE TITLE
Compiling error with latest assimp commit

### ISSUE THREAD

**Issue by AitorArd** [acgessler/assimp2json#6]
There is a problem with the last commit of assimp and your code: ExportFormatEntry jump fail to arguments conversions.

**Comment by acgessler** [comment]
Please provide the full error you're getting, as well as compiler version.

**Comment by AitorArd** [comment]
My visual studio 2013 output is this:

1>------ Operación Compilar iniciada: proyecto: assimp2json, configuración: Debug Win32 ------
1>  json_exporter.cpp
1>C:\Users\aardanza\Desktop\assimp2json\assimp2json\json_exporter.cpp(41): error C2665: 'Assimp::Exporter::ExportFormatEntry::ExportFormatEntry' : ninguna de las 3 sobrecargas pudo convertir todos los tipos de argumento
1>          C:\Users\aardanza\Desktop\assimp2json\assimp\include\assimp/Exporter.hpp(103): puede ser 'Assimp::Exporter::ExportFormatEntry::ExportFormatEntry(const char *,const char *,const char *,Assimp::Exporter::fpExportFunc,unsigned int)'
1>          al hacer coincidir la lista de argumentos '(const char [12], const char [61], const char [12], overloaded-function, unsigned int)'
========== Compilar: 0 correctos, 1 incorrectos, 3 actualizados, 0 omitidos ==========

I'm working into windows 7.

**Comment by acgessler** [comment]
Fixed now, apologies for addressing this so late.
